---
- name: install httpd
  hosts: centos-1 centos-2
  sudo: true
  tasks:
    - name: install package
      package:
        name: httpd
        state: present
    - name: create an index.html
      copy:
        content: "Hello World from {{ inventory_hostname }}"
        dest: /var/www/html/index.html
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: true
